### ISSUE TITLE
聊天消息存在 XSS / 接口未鉴权，导致可以随意遍历用户好友

### ISSUE THREAD

**Issue by wuhan005** [IcedSoul/WithMe#2]
大佬你好，偶然间在百度上搜到了你的这个聊天室，做的很棒！

我尝试着体验了一下，发现了一些问题：
## 聊天消息存在 XSS
用户发送的聊天信息未做 XSS 过滤，导致可以任意执行 JavaScript 代码。

发送者发送：
```
<script>alert(1);</script>
```
接受者 Web 端可以出现弹窗：

<img src="https://user-images.githubusercontent.com/12731778/51320947-64ceb700-1a9c-11e9-8cf6-e56ce30eb02a.PNG" width=30%/>

同样，在创建群填写信息那里，也是可以 XSS 注入的。

## 查询好友的接口未鉴权
通过给`http://119.23.212.211:8080/WithMe/getRelations`发送`POST`请求来获取用户的好友。
这里需要传入当前用户的 ID，即`userId`。
这里可以修改`userId`发送请求从而任意遍历用户的好友。
其中因为 ID 为 0 的管理员账户会默认添加所有用户为好友，因此管理员的好友就包含聊天室所有的账户信息。

同样，获取用户所加入群的接口`http://119.23.212.211:8080/WithMe/getUserGroups`也是没有鉴权的，导致可以随意查看。

**Comment by IcedSoul** [comment]
非常感谢你的告知。  
关于你所提到的两个问题，都是我在开发的时候没有考虑现在确实存在的。  
我会在最近在这个版本中解决这两个问题，也会在新版本中注意这两点，再次感谢。  
其中ID为0的管理员只是在在线演示系统中存在，download的代码不会存在自动加管理员这个逻辑。
